"""create articles table

Revision ID: 2801e6781783
Revises: a4188b322b0d
Create Date: 2026-07-14 19:00:25.132991

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2801e6781783"
down_revision: str | Sequence[str] | None = "a4188b322b0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("topic", sa.String(length=32), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "scraped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text_hash", name="uq_articles_text_hash"),
    )
    op.create_index("ix_articles_published_at", "articles", ["published_at"], unique=False)
    op.create_index(
        "ix_articles_topic_published_at", "articles", ["topic", "published_at"], unique=False
    )
    # op.drop_constraint(op.f('uq_feedback_prediction_id'), 'feedback', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('uq_feedback_prediction_id'), 'feedback', ['prediction_id'], postgresql_nulls_not_distinct=False)
    op.drop_index("ix_articles_topic_published_at", table_name="articles")
    op.drop_index("ix_articles_published_at", table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
