"""add predicted label and score to articles

Revision ID: 59d6acdf882d
Revises: 2801e6781783
Create Date: 2026-07-22 22:07:35.545506

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59d6acdf882d"
down_revision: str | Sequence[str] | None = "2801e6781783"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("predicted_label", sa.String(length=32), nullable=True))
    op.add_column("articles", sa.Column("predicted_score", sa.Float(), nullable=True))
    op.create_index(
        "ix_articles_predicted_label_published_at",
        "articles",
        ["predicted_label", "published_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_articles_predicted_label_published_at", table_name="articles")
    op.drop_column("articles", "predicted_score")
    op.drop_column("articles", "predicted_label")
    # ### end Alembic commands ###
