"""add sentiment and sentiment_score to articles

Revision ID: 994db2ded479
Revises: 59d6acdf882d
Create Date: 2026-07-24 16:48:35.116964

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "994db2ded479"
down_revision: str | Sequence[str] | None = "59d6acdf882d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("sentiment", sa.String(length=16), nullable=True))
    op.add_column("articles", sa.Column("sentiment_score", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "sentiment_score")
    op.drop_column("articles", "sentiment")
    # ### end Alembic commands ###
